### ISSUE TITLE
Roadmap to v1.0/stable release

### ISSUE THREAD

**Issue by animafps** [animafps/rustsynth#1]
Before releasing v1.0 would like to have near 100% coverage of the vapoursynth API or at least all developer facing functions/structs

## Structs

- [x] API
- [x] Core(Ref)
- [x] Map (Ownedmap, MapRef, MapRefMut)
- [ ] Map Iters (Keys, Values, Iter, IntoIter)
- [x] Node
- [x] Function
- [x] PluginFunction
- [x] Filter
- [x] Script environment
- [x] ScriptAPI
- [x] PluginAPI
- [x] VideoInfo
- [x] AudioInfo
- [x] Format
- [x] LogHandler
- [ ] ...

May need to rework how the API cache works before checking it off

## Functionality

- [x] Get API
- [x] Create Core (partial done need to document flags)
- [x] Create Map
- [x] Read keys from map
- [ ] Data subtypes
- [ ] Node subtypes
- [x] Read values from map
- [x] Read array values from map
- [x] Set array values to map
- [ ] Index map
- [x] Basic map handling
- [x] Set values in map (partial need to improve data, node and frame for subtypes)
- [x] Create keys in map
- [ ] Mutability of map through indexing
- [x] Get loaded plugins
- [x] Get plugin functions
- [x] invoke plugin functions
- [x] Create Nodes
- [x] Parse nodes
- [x] create Functions and by proxy pluginfunctions
- [x] Create script environment
- [x] eval script
- [x] get output from script environment
- [x] Log handling
- [x] create log event
- [x] Node infos
- [x] Load plugin
- [ ] Typed nodes
- [x] getFrameAsync (with native futures)
- [x] Macros for plugin creation
- [x] Map comsumes
- [ ] ...

## Unit Testing

- [ ] Map
- [ ] API
- [ ] Node
- [ ] VSScript
- [ ] Frame
- [ ] Filter
- [ ] Plugin
- [ ] Function
- [ ] PluginAPI

## Documentation

- [ ] Create overview API doc notes
- [ ] function specific overview notes
- [ ] Vapoursynth overview/architecture 
- [ ] Warnings/Errors
- [ ] Panics
- [ ] Safety limitations
- [x] App example (vspipe)
- [x] Plugin example
